### ISSUE TITLE
Crashed upon execution from the CLI

### ISSUE THREAD

**Issue by digen** [UprootLabs/unplug#6]
## Crashed output

```
$ java -jar unplug-0.1.jar
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at co.uproot.unplug.gui.GuiPackage$guiClient$d19e6806.main(guiClient.kt:19)
    at co.uproot.unplug.gui.GuiPackage.main(guiClient.kt:1)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 14 more
```
## Java Details

```
$ java -version
openjdk version "1.8.0_25"
OpenJDK Runtime Environment (Zulu 8.4.0.1-macosx) (build 1.8.0_25-b17)
OpenJDK 64-Bit Server VM (Zulu 8.4.0.1-macosx) (build 25.25-b02, mixed mode)
```
## Macbook and OS Specifications

```
Model Name: MacBook Pro
Processor Name: Intel Core i7
Processor Speed:    2.4 GHz
Memory: 8 GB
OS : Yosemite ( 10.10.1 ) 
```

**Comment by hrj** [comment]
Looks like Zulu builds are not packaging the JavaFX library.

@giltene can you confirm?

**Comment by giltene** [comment]
Correct. JavaFX is not part of Java SE, OpenJDK JDKs or JREs, or a standard part of a JDK or JRE. A It is also not part of the Java community process and has no formal specifications (and associated JSRs). It is simply a framework that is bundled with some versions of Oracle JDKs. It is also completely open source (hosted under OpenJDK). You can look at OpenJFK for details.

We haven't had many requests for an OpenJFX binary build.

Sent from my iPad

On Mar 7, 2015, at 6:50 PM, hrj <notifications@github.com<mailto:notifications@github.com>> wrote:

Looks like Zulu builds are not packaging the JavaFX library.

@giltenehttps://github.com/giltene can you confirm?

**Comment by hrj** [comment]
Thanks @giltene. I had no idea that JavaFX was a non-standard, extra bundle.

> We haven't had many requests for an OpenJFX binary build.

Please consider this as an informal request for it.
